### ISSUE TITLE
OpenAI Usage Tier 1 - "You exceeded your current quota, please check your plan and billing details"

### ISSUE THREAD

**Issue by albnsft** [vivekuppal/transcribe#101]
Hey, I would like to know what type of OpenAI subscription you have for those whose script works.
I upgraded my account to a Usage Tier 1 but still have the error message "You exceeded your current quota, please check your plan and billing details". Moreover, my number of api requests is still equal to 0, even though I've set the API key.

**Comment by vivekuppal** [comment]
I think you are likely looking at this URL - https://platform.openai.com/usage

Since today is Dec 1, I suspect OpenAI reset all usage numbers from November. Can change month to November to see usage in month of November.

**Comment by albnsft** [comment]
I started the Usage Ter 1 subscription today, my daily cost is equal to 0$.

**Comment by vivekuppal** [comment]
I believe OpenAI allows you to set monthly limit for spend. Can also set alerts once usage goes beyond a specific threshold.
You can set a limit you are comfortable with and over the course of time you will discover your spend, since it is dependent on usage more than anything else.
