### ISSUE TITLE
How to execute Deepgram?

### ISSUE THREAD

**Issue by aiking2222** [vivekuppal/transcribe#110]
Hey I see Deepgram API in parameters file.

I have added the deepgram API in override file.

But I am not able to execute it?

What command should I use?

**Comment by aiking2222** [comment]
Hi, tried doing the same and getting the following error, can you assist?

`C:\Users\prakh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
[INFO] Listening to sound from Microphone: #17 - Headset (WH-CH720N)
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Listening to sound from Speaker: #15 - Headphones (WH-CH720N) [Loopback]
[INFO] Adjusting for ambient noise from Default Speaker. Please play sound from Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
Traceback (most recent call last):
  File "C:\WINDOWS\system32\transcribe\app\transcribe\main.py", line 418, in <module>
    main()
  File "C:\WINDOWS\system32\transcribe\app\transcribe\main.py", line 344, in main
    create_transcriber(name=args.speech_to_text,
  File "C:\WINDOWS\system32\transcribe\app\transcribe\main.py", line 275, in create_transcriber
    model = model_factory.get_stt_model_instance(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WINDOWS\system32\transcribe\app\transcribe\../..\sdk\transcriber_models.py", line 48, in get_stt_model_instance
    return DeepgramSTTModel(config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WINDOWS\system32\transcribe\app\transcribe\../..\sdk\transcriber_models.py", line 295, in __init__
    from deepgram import Deepgram  # noqa:E402  pylint: disable=C0415,C0411
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'deepgram'`

**Comment by aiking2222** [comment]
I was able to run the app but getting this error - 

<img width="403" alt="image" src="https://github.com/vivekuppal/transcribe/assets/134321548/afb02bb9-2bab-4cc5-9782-7af285fa81f8">


Can you help?

**Comment by vivekuppal** [comment]
```
ModuleNotFoundError: No module named 'deepgram'
```
This error is because deepgram is not in requirements.txt. I will remediate that in the next PR.

For the next error for NoneType object, in the screenshot, confirm a few things
- Provide the complete output for the NoneType issue just like for the earlier issue
- Does the application work well with other STT options
- Does this error happen with the default code base or is it a modified code base
- Are you using VPN for connection to Deepgram servers

**Comment by j0n0w1ns** [comment]
I can use deepgram without any issues

`python main.py -stt deepgram`

**Comment by vivekuppal** [comment]
Likely an environmental issue
