### ISSUE TITLE
Incorrect API key error occurs 

### ISSUE THREAD

**Issue by KesavanWebrixtec** [vivekuppal/transcribe#129]
The program is ready after that Incorrect API key error occurs

![api](https://github.com/vivekuppal/transcribe/assets/117896195/b9ba1263-6f79-4c93-8e31-982d686bbb0a)
![api1](https://github.com/vivekuppal/transcribe/assets/117896195/c77aa4a0-7f1d-4bc6-a19f-8911f9c4383c)

**Comment by mang0sw33t** [comment]
Did you add API key in `parameters.yaml` or `override.yaml`

**Comment by KesavanWebrixtec** [comment]
Yes I a have done it @mang0sw33t

**Comment by vivekuppal** [comment]
Specificity of response will help with resolution of the issue. 
It is unclear where the API_KEY was added.

**Comment by mang0sw33t** [comment]
>Yes I a have done it @mang0sw33t
Confirm if it resolved the issue.
Close when issue is resolved.

**Comment by abhinavuppal1** [comment]
Just making sure, intent was to actually use a key for getting responses.
