### ISSUE TITLE
Can't register using the slack org in the readme

### ISSUE THREAD

**Issue by DawgZter** [vivekuppal/transcribe#138]
Hey i tried joining the slack org using the link in the readme but looks like you can only sign in with an exisiting account. No option to register.

**Comment by mang0sw33t** [comment]
A new user sees this interface on clicking the [join community link](https://transcribe-workspace.slack.com/channels/general)

![image](https://github.com/vivekuppal/transcribe/assets/153093451/179ee9d7-b82e-4d98-8ceb-d21d676d8427)

It has all options, use an existing gmail, apple account or use an email to join
What steps are you following

**Comment by DawgZter** [comment]
Yea so those options only work if you have already been registered into the org. Will not work if we haven't received an actual invite into the org.

**Comment by mang0sw33t** [comment]
Share a screenshot of what you see

**Comment by DawgZter** [comment]
Same thing it's just that if I try to login I will get this email.
<img width="661" alt="Screenshot 2024-01-15 at 3 10 47 pm" src="https://github.com/vivekuppal/transcribe/assets/22161246/a1390679-364a-47b3-b30d-09329079652d">

This is because as mentioned, this is a login/sign in link as opposed to a registeration link.

**Comment by mang0sw33t** [comment]
A new user to transcribe community sees this when attempting to login

![image](https://github.com/vivekuppal/transcribe/assets/11325412/0021f010-7a32-4f18-abd6-e1ad5b2ccbf9)

Share e-mail to use for registration with Vivek at his [LinkedIn](https://www.linkedin.com/in/vivekuppal/) or here
