### ISSUE TITLE
[Feature] Diarization support?

### ISSUE THREAD

**Issue by DawgZter** [vivekuppal/transcribe#139]
Could be interesting to include diarization support, so the LLM has the context of multiple speakers and which parts are spoken by who. I know deepgram already supports this in their transcription though, so maybe it's just a matter of changing up the settings on the api call and it's good to go? https://developers.deepgram.com/docs/diarization

**Comment by vivekuppal** [comment]
Getting diarization from Deepgram is fairly simple like you said, a matter of providing the correct config settings.
The code would need to be adjusted to support from current You, Speaker, to You, Speaker-1, Speaker-2, ..... Speaker-N.

I would be happy to help anyone if they want to take this on.
