### ISSUE TITLE
small download model link is same as base model

### ISSUE THREAD

**Issue by AnshulJ999** [vivekuppal/transcribe#14]
the small gdrive link is same as base model, and it leads to base model. please update it. thanks

**Comment by vivekuppal** [comment]
Thanks for reporting the issue @AnshulJ999 . 
The small model link is https://drive.google.com/file/d/1vhtoZCwfYGi5C4jK1r-QVr5GobSBnKiH/view?usp=drive_link, please use this one.
I will fix it in the next PR, or you are welcome to submit a PR as well.

**Comment by vivekuppal** [comment]
@AnshulJ999 we welcome feedback as you use the software.
