### ISSUE TITLE
Error when attempting to get a response from LLM.

### ISSUE THREAD

**Issue by instantchampion** [vivekuppal/transcribe#153]
I loaded Openai with min. credits and have GPT-4, getting this message:

Error when attempting to get a response from LLM.
Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

![image](https://github.com/vivekuppal/transcribe/assets/22304140/e89f08cd-042b-4344-988e-5c7f90ed4824)

**Comment by mang0sw33t** [comment]
Great to hear that the issue is resolved for you.
Share the solution for benefit of the whole community.

**Comment by boboboma** [comment]
how did you fix it?can you tell me?i have same problem .
