### ISSUE TITLE
error  "AttributeError: module 'openai' has no attribute 'OpenAI'"

### ISSUE THREAD

**Issue by Freddy23456** [vivekuppal/transcribe#159]
When i try to run the app I see this error:

[INFO] Using default microphone.
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Using default speaker.
[INFO] Listening to sound from Speaker: #16 - G257HL (NVIDIA High Definition Audio) [Loopback]
[INFO] Using Open AI Whisper API for transcription.
Traceback (most recent call last):
  File "C:\transcribe\app\transcribe\main.py", line 114, in <module>
    main()
  File "C:\transcribe\app\transcribe\main.py", line 30, in main
    au.create_transcriber(name=args.speech_to_text,
  File "C:\transcribe\app\transcribe\app_utils.py", line 164, in create_transcriber
    model = model_factory.get_stt_model_instance(
  File "C:\transcribe\app\transcribe\../..\sdk\transcriber_models.py", line 45, in get_stt_model_instance
    return APIWhisperSTTModel(stt_model_config=stt_model_config)
  File "C:\transcribe\app\transcribe\../..\sdk\transcriber_models.py", line 169, in __init__
    self.stt_client = openai.OpenAI(api_key=stt_model_config['api_key'], base_url=None)
AttributeError: module 'openai' has no attribute 'OpenAI'

**Comment by vivekuppal** [comment]
Please share the output of 
`pip -list`

**Comment by Freddy23456** [comment]
> Please share the output of
> `pip -list`

aiohttp                   3.9.3
aiosignal                 1.3.1
altgraph                  0.17.4
anyio                     4.3.0
async-timeout             4.0.3
asyncio                   3.4.3
attrs                     23.2.0
bandit                    1.7.7
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
customtkinter             5.2.2
darkdetect                0.8.0
dataclasses-json          0.6.4
deepgram-sdk              3.1.0
exceptiongroup            1.2.0
ffmpeg-python             0.2.0
filelock                  3.13.1
frozenlist                1.4.1
fsspec                    2024.2.0
future                    1.0.0
gTTS                      2.5.1
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
idna                      3.6
Jinja2                    3.1.3
llvmlite                  0.42.0
markdown-it-py            3.0.0
MarkupSafe                2.1.5
marshmallow               3.21.0
mdurl                     0.1.2
more-itertools            10.2.0
mpmath                    1.3.0
multidict                 6.0.5
mypy-extensions           1.0.0
networkx                  3.2.1
numba                     0.59.0
numpy                     1.24.3
openai                    0.27.6
openai-whisper            20230314
packaging                 23.2
pbr                       6.0.0
pefile                    2023.2.7
pip                       24.0
playsound                 1.2.2
PyAudioWPatch             0.2.12.6
pycparser                 2.21
Pygments                  2.17.2
pyinstaller               6.3.0
pyinstaller-hooks-contrib 2024.2
pyperclip                 1.8.2
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
regex                     2023.12.25
requests                  2.31.0
rich                      13.7.1
setuptools                63.2.0
sniffio                   1.3.1
soundfile                 0.12.1
stevedore                 5.2.0
sympy                     1.12
tiktoken                  0.3.1
torch                     2.2.1
tqdm                      4.66.2
typing_extensions         4.10.0
typing-inspect            0.9.0
urllib3                   2.2.1
verboselogs               1.7
Wave                      0.0.2
websockets                12.0
yarl                      1.9.4

**Comment by vivekuppal** [comment]
Seems like an issue of openai libraries at the incorrect version
```
openai 0.27.6
openai-whisper 20230314
```
update these libraries to the following version
```
openai                    1.11.1
openai-whisper            20231117
```

**Comment by vivekuppal** [comment]
>Unrelated question: if I run it through transcribe.exe will it run --api? will it use the actual whisper?

`python main.py --api` uses OpenAI API for STT
`python main.py` uses whisper with local STT

**Comment by mang0sw33t** [comment]
re-open for any further questions
