### ISSUE TITLE
About Chinese

### ISSUE THREAD

**Issue by Yrwxru** [vivekuppal/transcribe#161]
请问如何修改中文的prompt，因为我不希望他转录识别未繁体，并且我想修改初始化给chatgpt的引导词。
Please tell me how to modify the Chinese prompt, because I don't want it to be transcribed and recognized as Traditional Chinese, and I want to modify the initialization guide word for chatgpt.

**Comment by mang0sw33t** [comment]
> I don't want it to be transcribed and recognized as Traditional Chinese

Languages supported by OpenAI from this link - https://platform.openai.com/docs/guides/speech-to-text/quickstart

```
Afrikaans, Arabic, Armenian, Azerbaijani, Belarusian, Bosnian, Bulgarian, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Galician, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Kannada, Kazakh, Korean, Latvian, Lithuanian, Macedonian, Malay, Marathi, Maori, Nepali, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian, Urdu, Vietnamese, and Welsh.
```

Only one version of chinese language is supported. 
All of these languages are supported for Speech to Text conversion in Transcribe.

>I want to modify the initialization guide word for chatgpt
I do not understand what you are asking for

**Comment by Yrwxru** [comment]
I wish to preface our discourse by informing ChatGPT with a prompt similar to "Imagine yourself as an intrinsic product manager."

Thanks.

**Comment by mang0sw33t** [comment]
To add a custom prompt, add the following section to `override.yaml` file
```
OpenAI:
  system_prompt: "PROMPT TEXT"
```

**Comment by mang0sw33t** [comment]
With the latest code, add the following section to `override.yaml` file

```
OpenAI:
  system_prompt: "PROMPT TEXT"
```
