### ISSUE TITLE
Getting invalid_api_key error. 

### ISSUE THREAD

**Issue by souder** [vivekuppal/transcribe#179]
**Describe the bug**
I get the following error:
Error when attempting to get a response from LLM.
Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-0oJ1K***************************************cMnE. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}}
**To Reproduce**
I managed to install the necessary requirements and I can run the program both from the exe and through the .py.

I loaded 5$ dollars in openai.
I generated a new api key. 
I modified the override file with the generated api key.
I run the program and try to generate a response, but I get the error. 

**Expected behavior**
Being able to generate responses with the openai API

**Screenshots**
![image](https://github.com/vivekuppal/transcribe/assets/22256543/5cfc62d4-5dde-4aca-acce-a158973b125a)

![image](https://github.com/vivekuppal/transcribe/assets/22256543/20f4cad7-68bb-4aad-95a4-579991a5eded)

**Comment by mang0sw33t** [comment]
AFAICT there is some issue with the API key, either it is missing a character or something like that.

Above screenshot is for the exe, could you also provide a similar output for the latest code from github.

**Comment by souder** [comment]
Thanks for your answer, it works now.  It looks like a bad typo, I generated a new apy key and the problem disappeared.

**Comment by souder** [comment]
Thanks for your answer, it works now. It looks like a bad typo, I generated a new api key and the problem disappeared.
