### ISSUE TITLE
urgent: together.ai  api key incompatible with new code base updates

### ISSUE THREAD

**Issue by tan-banana** [vivekuppal/transcribe#183]
To reproduce the error, download the repo today and try to use together.ai as the llm. it will not work. this is due to recent changes made to the code. prior there was a loophole to use the openai key in the yaml as the api key (as together ai is meant to work).  
 like it goes ... open ai : 'together api key'  but that doesnt work now.
 
I tried 100 ways. not a developer so I cant edit the main code successfully besides the variables. it seems like a structural issue a small change maybe.

Original error message: 

[INFO] Speech To Text - Whisper using GPU: True
Traceback (most recent call last):
 
 File "C:\Users\transcribeUpdated\app\transcribe\main.py", line 125, in <module>
    main()
  File "C:\Users\transcribeUpdated\app\transcribe\main.py", line 68, in main   
    ui_components = ui.create_ui_components(root, config=config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\transcribeUpdated\app\transcribe\ui.py", line 494, in create_ui_components
    if not utilities.is_api_key_valid(api_key=api_key, base_url=base_url):
                                              ^^^^^^^
UnboundLocalError: cannot access local variable 'api_key' where it is not associated with a value

**Comment by mang0sw33t** [comment]
create a section in `override.yaml` file as follows

```
Together:
  api_key: 'API_KEY'
```

**Comment by tan-banana** [comment]
> create a section in `override.yaml` file as follows
> 
> ```
> Together:
>   api_key: 'API_KEY'
> ```
`Ok I put the api as together.ai but still get this same error`
 ` File "C:\Users\transcribeUpdated\app\transcribe\main.py", line 125, in <module>
    main()
  File "C:\Users\transcribeUpdated\app\transcribe\main.py", line 68, in main   
    ui_components = ui.create_ui_components(root, config=config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\transcribeUpdated\app\transcribe\ui.py", line 494, in create_ui_components
    if not utilities.is_api_key_valid(api_key=api_key, base_url=base_url):
                                              ^^^^^^^
UnboundLocalError: cannot access local variable 'api_key' where it is not associated with a value `

**Comment by vivekuppal** [comment]
Transcribe configuration is very flexible. There are several ways to achieve the desired behavior of using Together AI.

They way described in the previous comment is accurate

```
OpenAI:
  api_key: 'API_KEY'
  base_url: 'https://api.together.xyz/v1'
  ai_model: ' together model '
```

The underlying issue is that Together AI does not support the way we use to validate the API key. This was a recent change. 
I believe the issue has been fixed in https://github.com/vivekuppal/transcribe/pull/185 and your way of doing it should continue to work after that PR is merged.

**Comment by tan-banana** [comment]
ok thanks for the validation of the issue. Thank you!

**Comment by vivekuppal** [comment]
Issue should be resolved now

**Comment by tan-banana** [comment]
Resolved by new updates nice work thanks. sorry I couldn't fix it myself.

**Comment by j0n0w1ns** [comment]
Seems like this repo is serving some purpose to some extent. 
There are multiple ways to contribute to the repo. Could write code, write something good about it, star the repo, make a video about useful use cases people like it for.
