### ISSUE TITLE
ImportError: cannot import name 'configuration' from 'tsutils'

### ISSUE THREAD

**Issue by pramodvasireddy** [vivekuppal/transcribe#187]
ImportError: cannot import name 'configuration' from 'tsutils'

I tried to install tsutils still it is showing same issue. which version of TSUtil I should use

**Comment by mang0sw33t** [comment]
tsutils is a folder in the transcribe repo. 
The description seems to indicate that there is an issue with the environment set up

>I tried to install tsutils still it is showing same issue. which version of TSUtil I should use

Please provide details of what remediation was attempted. Some screenshots would be useful.

give us some insight into the dev environment and we might be able to help with this issue

**Comment by vivekuppal** [comment]
closing as environmental issue. We will need more details as illustrated above to help.
