### ISSUE TITLE
how to replace an existing LLM model with another one

### ISSUE THREAD

**Issue by Eva00062** [vivekuppal/transcribe#198]
Thank you for this detailed guide; it's so thorough that even a liberal arts student like me was able to follow the steps and succeed. I'd like to know how to replace an existing LLM model with another one. What should I do.

Due to the national restrictions by OpenAI, the current API key was obtained through special channels. For frequent future use, I would like to switch to China's Moonshot as the LLM to interact with. Could you provide some tips or suggestions on how to implement this feature? I look forward to your reply, thank you! 

Here is the link to the Moonshot API documentation for your reference: https://platform.moonshot.cn/docs/api-reference.

**Comment by vivekuppal** [comment]
Seems like the issue has been resolved. Reopen if you need further help.
