### ISSUE TITLE
The button at the bottom right cannot be clicked, and the content cannot be displayed

### ISSUE THREAD

**Issue by chenosyong** [vivekuppal/transcribe#205]
Hello friend, after installing transfer, I am unable to reply to the content displayed on the right side and the button below cannot be clicked. Can you tell me the reason? Thank you！
![240511213245](https://github.com/vivekuppal/transcribe/assets/45561559/b703c08a-5ae4-4e80-ba4c-398fc16b8156)

**Comment by vivekuppal** [comment]
This happens when the API key is not specified in `override.yaml`

**Comment by vivekuppal** [comment]
I believe this situation should be better now in the latest code base. Let us know if any further changes are required.
