### ISSUE TITLE
Error when attempting to get a response from LLM. list index out of range

### ISSUE THREAD

**Issue by chenosyong** [vivekuppal/transcribe#207]
After running properly for several times, an LLM error occurs, resulting in no reply displayed on the right. I do not know whether the agent is affected. Can you solve the problem?
![1212432](https://github.com/vivekuppal/transcribe/assets/45561559/9255b6af-447c-4afe-a781-4cde306d9907)

**Comment by abhinavuppal1** [comment]
Could you please share the output of the following command

`pip list`

The chosen language is chinese, which means the audio for speech to text is being interpreted as being in chinese. Making sure that was the intent. I do realize that language choice selection does not explicitly say that. Suggestions on that front are welcome.

**Comment by chenosyong** [comment]
Package      Version
------------ -------
distlib      0.3.8
filelock     3.14.0
pip          24.0
platformdirs 4.2.1
setuptools   65.5.0
virtualenv   20.26.2

**Comment by vivekuppal** [comment]
This does not seem right. There should be a lot more packages installed to have transcribe be functional.

**Comment by chenosyong** [comment]
What other packages do I need to install?

**Comment by vivekuppal** [comment]
All packages required for transcribe are in app\transcribe\requirements.txt file.

I see that you are using virtualenv, there likely are multiple packages installed inside of virtualenv.

Seems like the code you are using is modified to certain extent from the code in this repo. To be able to help effectively it might be best to share the code.

**Comment by chenosyong** [comment]
This is the installation process, is there any problem?

Uploading 2024-05-15 20-24-16-479.mp4…

**Comment by chenosyong** [comment]
Package              Version
-------------------- ---------
build                1.2.1
CacheControl         0.14.0
certifi              2024.2.2
chardet              5.2.0
charset-normalizer   3.3.2
cleo                 2.1.0
colorama             0.4.6
crashtest            0.4.1
distlib              0.3.8
dulwich              0.21.7
fastjsonschema       2.19.1
filelock             3.14.0
idna                 3.7
importlib_metadata   7.1.0
installer            0.7.0
jaraco.classes       3.4.0
keyring              24.3.1
more-itertools       10.2.0
msgpack              1.0.8
packaging            24.0
pexpect              4.9.0
pip                  24.0
pkginfo              1.10.0
platformdirs         4.2.1
poetry               1.8.3
poetry-core          1.9.0
poetry-plugin-export 1.8.0
ptyprocess           0.7.0
pyproject_hooks      1.1.0
pywin32-ctypes       0.2.2
rapidfuzz            3.9.0
requests             2.31.0
requests-toolbelt    1.0.0
setuptools           65.5.0
shellingham          1.5.4
tomlkit              0.12.5
trove-classifiers    2024.4.10
urllib3              2.2.1
virtualenv           20.26.2
zipp                 3.18.1

**Comment by vivekuppal** [comment]
This is an incomplete list of packages needed to run transcribe. E.g. numpy package is part of requirements.txt but I do not see it in the list. Transcribe does not use tomlkit but I see that in this list.

I am fairly certain the version of code you are using is different from what is in the transcribe repo. Please share code to continue thee conversation forward.
