### ISSUE TITLE
Can transcribe be adapted to translate language in real time? 

### ISSUE THREAD

**Issue by ryanoder** [vivekuppal/transcribe#225]
Context: I am working in Japan but do not speak Japanese. Many of the meetings that I sit in are conducted in Japanese and I need to have people translate and/or switch to english when they need my input. I would like to just have a continuous live translation of the discussion so I can follow along, and have tried solutions like PocketTalk and VoicePing but they both have issues.  GPT4o can do this but not in a continuous translation use-case (only for back-and-forth conversation snippets) and I also do not want the audio output, only text. 

I am also presently Mac user, but could obtain a windows machine if necessary for this purpose.

**Comment by mang0sw33t** [comment]
This is possible with Transcribe. Please share email to join the community or get in touch with [Vivek](https://www.linkedin.com/in/vivekuppal/) on LinkedIn to discuss further.

**Comment by cbellosoto** [comment]
i would like to join the community. cbellosoto@gmail.com

**Comment by ryanoder** [comment]
Ryan.Oder@gmail.com

**Comment by vivekuppal** [comment]
Invites sent

**Comment by vivekuppal** [comment]
There was an issue with the way I sent invites earlier, the invite emails were not sent.
Correct email invites were sent today.
