### ISSUE TITLE
KeyError: 'llm_response_interval'

### ISSUE THREAD

**Issue by steventangbc** [vivekuppal/transcribe#229]
I was able to run the app before but it seems like recent changes have made it stop working.

```
C:\Users\Alyssa\Documents\transcribe\app\transcribe>python main.py
Directory 'C:\Users\Alyssa\AppData\Roaming\viveku\Transcribe\/logs' already exists.
[INFO] Using default microphone.
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Using default speaker.
[INFO] Listening to sound from Speaker: #25 - Headphones (Bose QC Headphones) [Loopback]
[INFO] Speech To Text - Whisper using GPU: True
Traceback (most recent call last):
  File "C:\Users\Alyssa\Documents\transcribe\app\transcribe\main.py", line 77, in <module>
    main()
  File "C:\Users\Alyssa\Documents\transcribe\app\transcribe\main.py", line 64, in main
    aui = AppUI(config=config)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alyssa\Documents\transcribe\app\transcribe\appui.py", line 41, in __init__
    self.create_ui_components(config=config)
  File "C:\Users\Alyssa\Documents\transcribe\app\transcribe\appui.py", line 143, in create_ui_components
    self.update_interval_slider.set(config['General']['llm_response_interval'])
                                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'llm_response_interval'

C:\Users\Alyssa\Documents\transcribe\app\transcribe>
```

**Comment by mang0sw33t** [comment]
Please elaborate what you mean by `recent changes have made it stop working`. 
The latest version of the app while running using latest code in Github does not have this issue, at least not in my environment. 

If you are running at a specific git version besides the latest version, please provide further details. 
Also please share the file `parameters.yaml`, `override.yaml`. 
The issue seems to be that the parameter `llm_response_interval` is not correctly defined in parameters. 
For an accurate definition of this parameter see this link - https://github.com/vivekuppal/transcribe/blob/a06b563bdd731a147e08c27ddc46a99a8c9b3687/app/transcribe/parameters.yaml#L82 

Please note that spaces are important in the yaml file.

**Comment by steventangbc** [comment]
Initially, I thought the recent UI update changed several variable names. But after reading your reply, I realized that I have been using an older `parameters.yaml` file because it contained my model and prompt preferences. I hadn't notice that new variables like `llm_response_interval` were added. When using the `parameters.yaml` file from the latest version, I am able to run the app successfully again. (I would share the files requested, but the latest files I am using contain all default values and my API key which I wish to redact.)

This led to another problem however. I am not receiving any replies or inference and there are no error messages in the command line. 

![image](https://github.com/vivekuppal/transcribe/assets/94030446/f7e0d1e0-7f13-4e82-bf62-1925d716f480)

**Comment by steventangbc** [comment]
The latest working version with inference that I tried was 7f66a2b, presumably before the UI update. 

![image](https://github.com/vivekuppal/transcribe/assets/94030446/0983d67b-98cd-4cb8-84d3-f6a12cd18420)

**Comment by mang0sw33t** [comment]
The recommended workflow for changing parameters is to use `override.yaml` file. Out of the box, `override.yaml` file is empty.
Any parameters that need to be altered in `parameters,yaml` should be added to `override.yaml` in the same section, with the same parameter name.

E.g. If you want to change the parameter `llm_response_interval` to a different value add the following section to it

```
General:
  llm_response_interval: 20
```

Based on the description, I am fairly certain issue is in `parameters.yaml` file.
Recommended next steps are

- Compare the default `parameters.yaml` file to your copy of `parameters.yaml` file
- Any differences in the two can be added to `override.yaml`. 
- Restore the default `parameters.yaml` file

**Comment by steventangbc** [comment]
I followed your recommended steps and only modified `override.yaml` with the differences while restoring `parameters.yaml` to the default file. However, I still am not getting any responses. Also, is the new UI supposed to be missing the old buttons like "Suggest Responses Continuously" and "Suggest Response Now"?

![image](https://github.com/vivekuppal/transcribe/assets/94030446/8645880a-77b3-4911-8006-be664d669676)

**Comment by mang0sw33t** [comment]
>is the new UI supposed to be missing the old buttons like "Suggest Responses Continuously" and "Suggest Response Now"?

Seems like the application is not completely visible at the moment. Increase the size of the window, both in width and height and you will see the complete application.

**Comment by steventangbc** [comment]
Increasing the size of the window revealed all of the buttons. Many thanks! A suggestion I have is to make each section of the UI resizable and responsive so that on all screen sizes, the relevant information can be displayed according to preference.

**Comment by GuinanGuo** [comment]
> > make each section of the UI resizable and responsive so that on all screen sizes, the relevant information can be displayed according to preference
> 
> Great suggestion. We need a tcl UI expert to help us achieve that.
Hi bro
1，Has the issue of the UI not automatically displaying all buttons been resolved?
2，I would like to ask, in your README, there are two methods for running the program. I want to know if the 'Getting Started' section provides steps to run the code from your repository, while the steps in the 'Software Installation' section mean that you have packaged the code into an exe file, which can be run by directly clicking the exe file?
