### ISSUE TITLE
No LLM response issue

### ISSUE THREAD

**Issue by shivpowerbi** [vivekuppal/transcribe#232]
I tried entering a new model with llama3-8b-8192, and after starting the application at the initial stage, it provided me a response, but when I click on the don't suggest response button and then the back suggest response continually button, I got no LLM response at this time.
Did anyone got fix to this issue?
![image](https://github.com/vivekuppal/transcribe/assets/171033006/9127b066-3400-48e1-b705-b517682727c8)

**Comment by mang0sw33t** [comment]
Transcribe has the ability to retrieve LLM responses received earlier in the conversation. When you click on a specific conversation text, it will retrieve the earlier LLM responses corresponding to that row. 

The message `No LLM response corresponding to this row` means there is no LLM response for that row.
Now if you click on Suggest Response Now button, it should fetch a response from LLM.
