### ISSUE TITLE
Getting Multiple LLM response input

### ISSUE THREAD

**Issue by Hivra1** [vivekuppal/transcribe#233]
Can someone please assist me in fixing the issues? When the transcribe app runs, the AI model takes an api input of the first row or sentence as input and provides a real-time response relevant to it. Then, when it switches to take the second row as input, it takes the first and second row context as input and provides a response based on the two responses. Similarly, when it moves forward to take the third row context, it takes input as the first, second, and third row context.
[api_logs.txt](https://github.com/user-attachments/files/15816488/api_logs.txt)

**Comment by mang0sw33t** [comment]
What is the question?
Seems like you have made significant changes to the underlying code, please elaborate on those changes as well.

**Comment by Hivra1** [comment]
Initially, i attempted to change the LLM model on **override.yaml** with the gemma it 2b model from chatgpt. Afterwards, when I tried to use the transcribe application, it gave me Response in real time for the first row of context based on input. however, for the second row of context, response based on input of text from the first and second rows

As an example:
I require a real-time response for just the most recent word sentences, which is indicated in the image below. The system accepts input from both the most recent and earlier sentences, providing a response for each.
![image](https://github.com/vivekuppal/transcribe/assets/143814587/1a441f30-d99e-41f8-b625-9a4d199f3b6d)

**Comment by mang0sw33t** [comment]
In the file `constants.php` change the below line
This determines how many phrases are sent to LLM for context. I would recommend using at least 2-3 phrases

```
MAX_TRANSCRIPTION_PHRASES_FOR_LLM = 12
```

I think this parameter should be made configurable in `parameters.yaml` file

**Comment by Hivra1** [comment]
I followed your instructions and updated the value in constants.py. However, now when I try to open the application, I receive a different type of issue. 
![image](https://github.com/vivekuppal/transcribe/assets/143814587/3d3a2c09-d0f9-4004-aad0-445b8009ecfa)

**Comment by mang0sw33t** [comment]
Please share `parameters.yaml` file and `override.yaml` file.

If you want to speed up resolution of the issue, please join the community.
For joining the community please share e-mail here or get in touch with [Vivek](https://www.linkedin.com/in/vivekuppal/) on LinkedIn

**Comment by Hivra1** [comment]
Here are the files. 
[override.yaml.txt](https://github.com/user-attachments/files/15827513/override.yaml.txt)
[parameters.yaml.txt](https://github.com/user-attachments/files/15827516/parameters.yaml.txt)

Please share the community invite link to this mail: Hivra2409@gmail.com

**Comment by mang0sw33t** [comment]
Invite sent to above email. Talk to you in the community channel.

**Comment by mang0sw33t** [comment]
Confirmed with the user issue resolved. issue was in formatting of the `yaml` file.
