### ISSUE TITLE
The UI interface does not match the one in the tutorial.

### ISSUE THREAD

**Issue by GuinanGuo** [vivekuppal/transcribe#238]
Hello, brother. After I ran the code, the UI interface that appeared looked like the one in Figure 1. It seems to have no functionality. However, the interface in the YouTube video, as shown in Figure 2, has a lot of features. What could be the reason for this?

Figure 1：
![c9efa5645c6aaf6a2724d5029fba6646](https://github.com/vivekuppal/transcribe/assets/115399025/f7eb09bd-3d52-4292-8110-127163b6309b)

Figure 2:
<img width="1674" alt="截屏2024-07-02 10 40 19" src="https://github.com/vivekuppal/transcribe/assets/115399025/32d0632d-a11a-4002-8b9b-532e5fedfaf0">

**Comment by vivekuppal** [comment]
If you were to increase the breadth, width of the application it will show the rest of the UI as well.

**Comment by GuinanGuo** [comment]
> If you were to increase the breadth, width of the application it will show the rest of the UI as well.

Thank you for your reply, but I would like to know if there is a solution that allows all the buttons to be automatically displayed as soon as the UI interface pops up.

**Comment by GuinanGuo** [comment]
> If you were to increase the breadth, width of the application it will show the rest of the UI as well.

And, in the README, there are two methods for running the program. I want to know if the 'Getting Started' section means that it provides steps to run the code from your repository, while the 'Software Installation' section mean that you have packaged the code into an exe file, which can be run by directly clicking the exe file?

**Comment by vivekuppal** [comment]
Yes, you got that right.

**Comment by GuinanGuo** [comment]
> Yes, you got that right.

thanks bro
