### ISSUE TITLE
Operating applications problem

### ISSUE THREAD

**Issue by andyoso** [vivekuppal/transcribe#239]
Thank you for your sharing. I'd like to ask how I can use this software to input my own notes for AI to learn from, so that when I encounter problems, it can search the notes and provide answers based on keywords.

**Comment by GuinanGuo** [comment]
Thank you for your sharing, and I have a question. A feature should be added that allows users to correct and edit their questions when speech recognition is inaccurate, then input the corrected question to GPT to receive the correct answer.

**Comment by abhinavuppal1** [comment]
Feature for editing of transcripts has been added.
