### ISSUE TITLE
Filling in the correct  Api key  will crash.

### ISSUE THREAD

**Issue by moyulengtu** [vivekuppal/transcribe#246]
I configured the right Api key in override.yaml.But when I run transcribe.exe    it will crashes.
However, when override.yaml is not filled with anything, it will run successfully.
What should I do, please help me
![0001](https://github.com/user-attachments/assets/3bc8587f-3e97-4114-bcf6-5e87acc6003a)
![0002](https://github.com/user-attachments/assets/20e7f39c-0f5b-4859-8f50-dda7e94332c2)

**Comment by Tang-Steven** [comment]
Try entering your key without the quotes.

**Comment by moyulengtu** [comment]
> 尝试输入不带引号的密钥。

OpenAI:
   api_key: sk-proj-TtWPpG5WgpXXXXXXXXXXXXXXXXXXzdVlvjfVk6yn79IA4

I changed it to this, and it still flashed.

https://github.com/user-attachments/assets/a7a2ef2a-f63a-4404-8ee7-c3c02420cf73

**Comment by moyulengtu** [comment]
By the way, does this app have to require a GPT4-0 API key interface?

**Comment by vivekuppal** [comment]
Use an earlier model like gpt-3.5-turbo and everything will work as anticipated.
To understand the details of the issue you are encountering please see this thread on openAI forums - https://community.openai.com/t/openai-error-invalidrequesterror-the-model-gpt-4-does-not-exist-or-you-do-not-have-access-to-it/376230

Also see this comment for a user who encountered a similar issue 
https://github.com/vivekuppal/transcribe/issues/171#issuecomment-1994059623

**Comment by moyulengtu** [comment]
> Use an earlier model like gpt-3.5-turbo and everything will work as anticipated. To understand the details of the issue you are encountering please see this thread on openAI forums - https://community.openai.com/t/openai-error-invalidrequesterror-the-model-gpt-4-does-not-exist-or-you-do-not-have-access-to-it/376230
> 
> Also see this comment for a user who encountered a similar issue [#171 (comment)](https://github.com/vivekuppal/transcribe/issues/171#issuecomment-1994059623)

I see what you mean, the reason for the problem may be because I don't have credit remaining.
![Snipaste_2024-07-20_22-48-32](https://github.com/user-attachments/assets/735f0fc3-474d-49bd-b8b1-b5ac08f0a270)
Well, it looks like I'm going to have to get a Visa international debit card.

It is a great honor to communicate and discuss with you, thank you~

Finally, can I make a small suggestion that I hope to add the Chinese (Simplified) language pack in future updates. Although there is already a Chinese (traditional) language pack, it looks a little inconvenient.

**Comment by mang0sw33t** [comment]
Seems like you are in China. There are a lot of OpenAI compatible providers in China. You can use an OpenAI compatible provider in China if that is easier for you. 

The supported languages for transcribe are at - https://platform.openai.com/docs/guides/speech-to-text/supported-languages. If OpenAI adds support for Chinese (Simplified), then we should be able to support that as well.

**Comment by abhinavuppal1** [comment]
No open questions in this issue anymore.
