### ISSUE TITLE
Irrelevant Text Issue

### ISSUE THREAD

**Issue by Hivra1** [vivekuppal/transcribe#253]
Can someone please assist me with this issue? I keep getting the following text as in speaker irrelevant to what I have requested for, and this message keeps appearing. For example, I asked a query about what SQL is, but the application either replaces it with the text below with multiple repetitions or with a thank you message. Kindly help me resolve the issue
![image](https://github.com/user-attachments/assets/f0c12301-61c4-40d4-bd5c-80bec89f5e70)

**Comment by mang0sw33t** [comment]
This issue is being discussed in the community channel. 
Follow it there
https://transcribe-workspace.slack.com/archives/C05LEAY7MG8/p1724692975789719
