### ISSUE TITLE
Refer to models on the OpenAI site instead of storing them on our servers

### ISSUE THREAD

**Issue by vivekuppal** [vivekuppal/transcribe#29]
Currently Transcribe allows use of tiny, base, small models of OpenAI. 
In addition to these models OpenAI also publishes medium, large, large-v1, large-v2 models. 
Location of these models is specified in https://github.com/vivekuppal/transcribe/blob/main/main.py 

We can do the following
- Update Transcribe source to refer to the models at their original location
- Allow user to use medium, large, large-v1, large-v2 models using cmd line args, though give a warning that they would need powerful computers to use medium and higher models
- Delete the models from our gdrive location

This has the added benefit that we do not have to update the models regularly on our end

**Comment by vivekuppal** [comment]
Resolved with PR #43

**Comment by sdhreddy** [comment]
Hi, what is the command line argument to use different models?

**Comment by Adarsha-gg** [comment]
> Hi, what is the command line argument to use different models?

@sdhreddy  
 -m {model's name} when running the script must work

**Comment by sdhreddy** [comment]
so to run a large model, is it -m {large} ? can you please list the syntax for all the  models?

**Comment by vivekuppal** [comment]
Please try the following

`python main.py -h`

It will list the available options for different command line arguments.
