### ISSUE TITLE
executing python main.py --api takes too long

### ISSUE THREAD

**Issue by TayoGitCat** [vivekuppal/transcribe#32]
executing python main.py --api takes too long to load

**Comment by vivekuppal** [comment]
- Please quantify too long. Is it 15s, 2 minutes, 10 minutes.
- Please share the output on command line when executing main.py.
- Is the behavior as expected without the api option. 
- How much time does it take with or without the --api option

**Comment by vivekuppal** [comment]
tagging @godvmxi since it seems like they ran into the same issue and were investigating it

**Comment by vivekuppal** [comment]
In my investigations thus far, use of --api flag has no impact on this behavior. @TayoGitCat can you confirm.

**Comment by 1314qiang** [comment]
> 到目前为止，在我的调查中，使用--API标志对此行为没有影响。@TayoGitCat你可以确认一下。

![屏幕截图 2023-07-26 132609](https://github.com/vivekuppal/transcribe/assets/115726095/27345f42-146f-4d27-81fc-5db2d1ea4d8b)
![屏幕截图 2023-07-26 132627](https://github.com/vivekuppal/transcribe/assets/115726095/812cf5d5-7caa-402c-8b03-d653835ce4f4)

**Comment by vivekuppal** [comment]
感谢您确认 --API 标志没有影响。

我无法获得该问题的一致重现性。
在我的调查中我得出了这个结论
根本问题在于类/行

```
def adjustment_for_ambient_noise(self, 来源: 麦克风, 持续时间: int=1):
    buffer = source.stream.read(source.CHUNK)
```

问题是stream.read是一个阻塞调用。
选择默认麦克风时，麦克风会拾取环境噪音，并且此方法会返回。
使用非默认麦克风时，读取方法会阻塞，直到执行某些操作以使麦克风拾取一些噪音。
注释该行将减少应用程序启动时的任何延迟。
我一直没有遇到此问题，因此无法 100% 确认这将解决该问题。
如果问题在某些设置中始终可以重现，那么能够验证它就太好了。

**Comment by vivekuppal** [comment]
The issue of delay in starting the application when non default microphone is selected has been resolved with PR #45 .
Please validate.
Closing the issue. Please re-open if the issue persists.
