### ISSUE TITLE
Why did it happen

### ISSUE THREAD

**Issue by 1314qiang** [vivekuppal/transcribe#38]
![屏幕截图 2023-07-26 132627](https://github.com/vivekuppal/transcribe/assets/115726095/d0b3dd60-f43d-475b-afa3-a22d19902122)

![屏幕截图 2023-07-26 132627](https://github.com/vivekuppal/transcribe/assets/115726095/858d0abe-6dc8-46a2-9ede-eadc0a35ed6d)

**Comment by vivekuppal** [comment]
I believe this issue has been resolved, please confirm.
If the issue is not resolved, please re-open. 

Thanks for reporting the defect.
