### ISSUE TITLE
Not able to save API key in yaml file

### ISSUE THREAD

**Issue by sdhreddy** [vivekuppal/transcribe#46]
I am not able to save my Open API key in parameters.yaml file.  I get permission denied , file cannot be saved in Transcribe directory.  Without using my API key, it is not answering any of the questions.  I do get error message in powershell that API key is needed.

**Comment by vivekuppal** [comment]
Can use the cmd line argument `-k` to provide the key.
E.g.
````
python main.pi --api -k <OpenAI Key>
```
This will allow to continue using transcribe

**Comment by sdhreddy** [comment]
I get the error below with the cmd line argument -k to provide the key 

"AppData\Local\Programs\Python\Python311\python.exe: can't open file 'C:\\WINDOWS\\system32\\transcribe\\main.pi': [Errno 2] No such file or directory"

**Comment by sdhreddy** [comment]
It works, ty !

**Comment by vivekuppal** [comment]
Glad to hear you were able to resolve this issue. 
I added an enhancement request #47 to make this better.
