### ISSUE TITLE
Support for Deepgram API for transcription?

### ISSUE THREAD

**Issue by DawgZter** [vivekuppal/transcribe#53]
I hear that Deepgram is a a more accurate, faster and cheaper ASR than Whisper. Maybe this is something worth exploring?

https://deepgram.com/

**Comment by vivekuppal** [comment]
This is a great suggestion. Deepgram looks very interesting.
I see this link about some of the capabilities of Deepgram - https://deepgram.com/compare-openai-whisper-alternatives
I do not have definitive info on the quality of Deepgram transcription.
Would be great to get some data on transcription quality before investing time towards it.

If you have experience with some of the other aspects of git repo maintenance like releases, pypi packages, unit tests etc. it would be great to put that experience to use here :-).
