### ISSUE TITLE
Not able to execute program

### ISSUE THREAD

**Issue by sdhreddy** [vivekuppal/transcribe#59]
Getting this error when trying to run program

PS C:\WINDOWS\system32\transcribe> python main.py --api
Traceback (most recent call last):
  File "C:\WINDOWS\system32\transcribe\main.py", line 10, in <module>
    from GPTResponder import GPTResponder
  File "C:\WINDOWS\system32\transcribe\GPTResponder.py", line 5, in <module>
    import GlobalVars
  File "C:\WINDOWS\system32\transcribe\GlobalVars.py", line 5, in <module>
    from audio_player import AudioPlayer
  File "C:\WINDOWS\system32\transcribe\audio_player.py", line 9, in <module>
    import playsound
ModuleNotFoundError: No module named 'playsound'

**Comment by vivekuppal** [comment]
I did these steps

```
git clone https://github.com/vivekuppal/transcribe.git
python -m venv venv
cd venv
Scripts\activate.bat
cd ..
pip install -r requirements.txt
python main.py --api
```

The user interface came up correctly and I was able to use the program.
This makes me believe there is an issue with the environment.

Please describe how you created the environment for transcribe.
Also please provide the output for the following command

`pip list`

**Comment by sdhreddy** [comment]
I was able to use the program till yesterday, All I did was to update the transcribe repository with latest changes using git pull.  Since then , I am getting the error above.

pip list

Package                   Version
------------------------- -----------
aiohttp                   3.8.5
aiosignal                 1.3.1
altgraph                  0.17.3
async-timeout             4.0.2
attrs                     23.1.0
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
colorama                  0.4.6
customtkinter             5.1.3
darkdetect                0.8.0
ffmpeg-python             0.2.0
filelock                  3.12.2
frozenlist                1.4.0
future                    0.18.3
idna                      3.4
Jinja2                    3.1.2
llvmlite                  0.40.1
MarkupSafe                2.1.3
more-itertools            10.0.0
mpmath                    1.3.0
multidict                 6.0.4
networkx                  3.1
numba                     0.57.1
numpy                     1.24.3
openai                    0.27.6
openai-whisper            20230314
pefile                    2023.2.7
pip                       23.2.1
PyAudioWPatch             0.2.12.5
pycparser                 2.21
pyinstaller               5.13.0
pyinstaller-hooks-contrib 2023.6
pyperclip                 1.8.2
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
regex                     2023.6.3
requests                  2.31.0
setuptools                65.5.0
soundfile                 0.12.1
sympy                     1.12
tiktoken                  0.3.1
torch                     2.0.1+cu117
tqdm                      4.65.0
typing_extensions         4.7.1
urllib3                   2.0.4
Wave                      0.0.2
yarl                      1.9.2

**Comment by vivekuppal** [comment]
That explains the issue.
playsound library was introduced in the last couple of PRs.
Please do the following again and that should resolve the issue

`pip install -r requirements.txt`

**Comment by sdhreddy** [comment]
Thanks, that helped.  But now I am not able to get continuous responses.  I get this error below when I click "Suggest Continuous Responses" 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 553, in _clicked
    self._command()
  File "C:\WINDOWS\system32\transcribe\ui.py", line 46, in freeze_unfreeze
    self.global_vars.freeze_button.configure(
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 441, in configure
    super().configure(require_redraw=require_redraw, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 133, in configure
    check_kwargs_empty(kwargs, raise_error=True)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['value'] are not supported arguments. Look at the documentation for supported arguments
