### ISSUE TITLE
Check out vocode

### ISSUE THREAD

**Issue by DawgZter** [vivekuppal/transcribe#62]
Hey I just stumbled on a repo that shares similar functionalities with Transcribe. Might be worth checking it out for inspiration:
https://github.com/vocodedev/vocode-python/

**Comment by vivekuppal** [comment]
Thanks, I will. 
Much appreciated!

**Comment by DawgZter** [comment]
@vivekuppal  Also just to add they do have a benchmarking tool for speech to text services.

https://github.com/vocodedev/vocode-python/blob/2060680b4bfca961046983fe136842a5af77e151/playground/streaming/benchmark.py#L565

Based on this tool and anecdotes within the Vocode community it seems like Microsoft Azure performs the best on both speed and accuracy. So something worth considering in the future if you want to make improvements on that front.

**Comment by mang0sw33t** [comment]
we checked it out
