### ISSUE TITLE
Support for Deepgram API for transcription

### ISSUE THREAD

**Issue by vivekuppal** [vivekuppal/transcribe#69]
Add support for Deepgram API for transcription.
Some reference implementations are available at 

Client Application based implementation
https://github.com/vocodedev/vocode-python/blob/2060680b4bfca961046983fe136842a5af77e151/vocode/streaming/transcriber/deepgram_transcriber.py#L126

Browser based implementation
https://deepgram.com/learn/live-transcription-mic-browser

**Comment by DawgZter** [comment]
Looks like they just updated their models: https://deepgram.com/learn/nova-2-speech-to-text-api

**Comment by vivekuppal** [comment]
In benchmark tests I have done thus far deepgram is much faster than whisper for sure. Sometimes as much as 10x faster. 
Added sample code for deepgram API transcription in PR #85. 

I am getting issues with SSL certificates on some windows systems, see comments here 
https://github.com/vivekuppal/transcribe/blob/99e83d7678e178524ec89f6f36538ba381da7e7e/examples/deepgram/deepgram_speech_2_text.py#L11

Would be great if you can try out the sample code and see if it works for you without those errors.

FYI @DawgZter
