### ISSUE TITLE
python main.py --api takes a long time

### ISSUE THREAD

**Issue by jackokeefe11** [vivekuppal/transcribe#71]
I have been running the code for around 10 minutes, and nothing has appeared. I saw some other people had the issue, but I am curious as to how long it should take. Here is my output: 

[INFO] Listening to sound from Microphone: #9 - Microphone (High Definition Audio Device)
[INFO] Listening to sound from Speaker: #8 - Speakers (High Definition Audio Device) [Loopback]
[INFO] Adjusting for ambient noise from Default Speaker. Please play sound from Default Speaker...

It is stuck there, there is no error.

**Comment by Adarsha-gg** [comment]
@jackokeefe11 
playing a random sound such as a youtube video or spotify should solve it.

**Comment by jackokeefe11** [comment]
I figured out the issue, I assumed it would take any input for sound, but because I am using a Windows VM from Mac, it will not pick up sound if you play it outside of the VM. I played sound within it, and it worked right away.
