### ISSUE TITLE
GPT Responses

### ISSUE THREAD

**Issue by sdhreddy** [vivekuppal/transcribe#76]
Is there any way we can save GPT responses so that we can see the history .  This would help as sometimes the speaker input is so fast that GPT responses keep updating and we are not able to see all the previous responses.

**Comment by vivekuppal** [comment]
Do you wish to persist just GPT responses or speaker input as well

**Comment by sdhreddy** [comment]
GPT response are priority.  Speaker Input , I believe cant be saved, because we are clearing that every 30 seconds per PR 72.  If you can save Speaker Input in a file for later viewing, even after it clears the speaker input that would be awesome !

**Comment by vivekuppal** [comment]
Some of these items have been discussed in a messaging channel where we had similar conversations before. If you are interested in discussing with more participants, message me here or on linkedin (https://www.linkedin.com/in/vivekuppal/) with your email so you can be added to the discussion group as well.

**Comment by sdhreddy** [comment]
Message you on Linkedin, thanks!

**Comment by vivekuppal** [comment]
The original request is to save all GPT responses. We could do that in a separate file. Would that help with your use case.

**Comment by sdhreddy** [comment]
Yeah that would be great, would i be able to view the file while the conversation is going on or does it have to end?

**Comment by vivekuppal** [comment]
The way I am thinking about it is
- Application will write all responses to a text file
- Application UI will continue to show the last response as it does now
- Can use a text editor to open the file and view all responses from LLM. Can use something like notepad++ which refreshes the file as the text changes.

**Comment by sdhreddy** [comment]
that would work for viewing the history ! thanks !

**Comment by vivekuppal** [comment]
Resolved in PR #81
