### ISSUE TITLE
Do we need paid version of CHATGPT?

### ISSUE THREAD

**Issue by prashantraghav12** [vivekuppal/transcribe#84]
You exceeded your current quota, please check your plan and billing details.
string indices must be integers, not 'str'
You exceeded your current quota, please check your plan and billing details.
string indices must be integers, not 'str'
You exceeded your current quota, please check your plan and billing details.
string indices must be integers, not 'str'
You exceeded your current quota, please check your plan and billing details.
string indices must be integers, not 'str'
You exceeded your current quota, please check your plan and billing details.
string indices must be integers, not 'str'

**Comment by vivekuppal** [comment]
Please specify the command line parameters for running transcribe.
From the looks of it, it seems like the OpenAI credits are used up.
It would be best to discuss this in an interactive manner. 

Please share e-mail or ping me on linkedin https://www.linkedin.com/in/vivekuppal/
so you can be added to the messaging channel for discussing such issues

**Comment by vivekuppal** [comment]
Offline discussions with user

1. They were using `-api` option to run the program. Using this option means the Speech to Text aspect uses Online Whisper API, which uses OpenAI credits and they need to be bought.
2. Using ChatGPT responses also requires OpenAI credits.

The Speech to Text aspects do not require OpenAI credits without the `-api` option on command line.

Closing the issue.
Please re-open if we need further discussion.
