### ISSUE TITLE
Special modifications

### ISSUE THREAD

**Issue by cyberninja13** [vivekuppal/transcribe#96]
I am interested in the project to work on adding an additional feature that could benefit the project for everyone as well

I want you to add a feature and you will be given an amount of money
Better than hiring a programmer or freelancer to do it
You are the owners of the project and you deserve it

I do not know how to contact you and I did not see contact information

**Comment by vivekuppal** [comment]
You can contact me using LinkedIn at https://www.linkedin.com/in/vivekuppal/

**Comment by vivekuppal** [comment]
We will open appropriate issues, PRs as required for desired functionality
